# Generated by Django 4.2.3 on 2024-03-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_profile_old_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Perfil'},
        ),
    ]
