# Generated by Django 4.2.3 on 2023-08-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='categoria',
            field=models.CharField(choices=[('MOUNTAIN', 'Mountain'), ('ROAD', 'Road'), ('GRAVEL', 'Gravel')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
