# Generated by Django 4.2.3 on 2023-08-22 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_bikes_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='data_fotografia',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='descricao',
            field=models.CharField(max_length=300),
        ),
    ]
