# Generated by Django 4.2.3 on 2024-03-27 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_pedido_itempedido'),
        ('bikes', '0007_alter_bikes_options_alter_bikes_categoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bikes',
            new_name='Produto',
        ),
    ]
